data:
  pkl_path: 'examples/outputs/veri776.pkl'
  train_size: (256, 256)
  valid_size: (256, 256)
  train_num_workers: 16  
  test_num_workers: 4  
  batch_size: 64 
  with_mask: True
  for_vanet: True
  vanet_backbone: resnet


loss:
  losses: ["id", "triplet", "center"]
#  losses: ["triplet"]


train:
  epochs: 120


test:
  remove_junk: True
  lambda_: 0.0
  vis_save_path: '/liushichao/VANet_based_PVEN/results_vis/single_branch'
  model_path: '/liushichao/VANet_based_PVEN/results/vanet_single-branch_resnet50_bag-of-tricks_3/model_120.pth'

device: 'cuda'
output_dir: '/liushichao/VANet_based_PVEN/results/vanet_single-branch_resnet50_bag-of-tricks'
