data:
#  pkl_path: '/liushichao/MY_PVEN/examples/outputs/veri776.pkl'
  pkl_path: 'examples/outputs/veri776.pkl'
  train_size: (224, 224)
  valid_size: (224, 224)
  train_num_workers: 16  
  test_num_workers: 4  
  batch_size: 64 
  with_mask: True
  for_vanet: True
  vanet_backbone: googlenet 

loss:
  losses: ["id", "triplet"]
#  losses: ["triplet"]

test:
  remove_junk: True
  lambda_: 0.0
  vis_save_path: '/liushichao/VANet_based_PVEN/results_vis'
  model_path: '/liushichao/VANet_based_PVEN/results/vanet_googlenet_wo_idloss_1/optimizer_200.pth'

device: 'cuda'
output_dir: '/liushichao/VANet_based_PVEN/results/vanet_googlenet_w_idloss'
